export interface Room {
  id: string;
  number: string;
  capacity: number;
  hasPrivateBathroom: boolean;
  isSoldOut?: boolean;
  currentOccupancy?: number; // Current number of people in the room (e.g., 1 for 1/2)
  coordinates: {
    x: number; // percentage of image width
    y: number; // percentage of image height
    width: number; // percentage of image width
    height: number; // percentage of image height
  };
  // Additional room details
  floor: number;
  bedType: string; // e.g., "2 single beds", "1 queen bed", "1 single bed"
  bathroomNumber: number;
  bathroomType: "private" | "shared"; // "private" or "compartido"
  roomType: "shared" | "individual"; // "compartida" or "private" (individual)
  roomSize: "small" | "large"; // "pequeña" or "grande"
  sotiQualification: number;
  beds: number;
  sharedBathroom: number;
  quality: number;
  roomPrice: number; // precio room
  pricePerPerson: number; // precio pax
  imageUrl?: string; // Optional image URL
}

export interface FloorData {
  floorNumber: number;
  floorPlanPath: string;
  rooms: Room[];
}

// Room data - coordinates will need to be adjusted based on the actual floor plan
// Coordinates are in percentages (0-100) relative to the image dimensions
export const floorsData: FloorData[] = [
  {
    floorNumber: 0,
    floorPlanPath: "/floor-plan-2.svg", // Image from Piso 2
    rooms: [
      {
        id: "floor-0-room-9",
        number: "Habitación 9",
        capacity: 1,
        hasPrivateBathroom: true,
        isSoldOut: true,
        floor: 0,
        bedType: "1 single bed",
        bathroomNumber: 9,
        bathroomType: "private",
        roomType: "individual",
        roomSize: "small",
        sotiQualification: 8.5,
        beds: 1,
        sharedBathroom: 1,
        quality: 1,
        roomPrice: 550,
        pricePerPerson: 550,
        imageUrl: "/room-images/Hab 9.png",
        coordinates: {
          x: 25.76,
          y: 53.28,
          width: 8.90,
          height: 16.67,
        },
      },
      {
        id: "floor-0-room-10",
        number: "Habitación 10",
        capacity: 2,
        hasPrivateBathroom: true,
        isSoldOut: true,
        floor: 0,
        bedType: "1 queen bed",
        bathroomNumber: 10,
        bathroomType: "private",
        roomType: "individual",
        roomSize: "large",
        sotiQualification: 10,
        beds: 1,
        sharedBathroom: 1,
        quality: 1,
        roomPrice: 650,
        pricePerPerson: 650,
        imageUrl: "/room-images/Hab 10.png",
        coordinates: {
          x: 18.3,
          y: 36.5,
          width: 18,
          height: 20.9,
        },
      },
      {
        id: "floor-0-room-11",
        number: "Habitación 11",
        capacity: 1,
        hasPrivateBathroom: true,
        isSoldOut: true,
        floor: 0,
        bedType: "1 single bed",
        bathroomNumber: 11,
        bathroomType: "private",
        roomType: "individual",
        roomSize: "small",
        sotiQualification: 8.5,
        beds: 1,
        sharedBathroom: 1,
        quality: 1,
        roomPrice: 550,
        pricePerPerson: 550,
        imageUrl: "/room-images/Hab 11.jpg",
        coordinates: {
          x: 33.10,
          y: 22.86,
          width: 13.38,
          height: 12.55,
        },
      },
    ],
  },
  {
    floorNumber: 1,
    floorPlanPath: "/floor-plan-4.svg", // Image from Piso 4
    rooms: [
      {
        id: "floor-1-room-1",
        number: "Habitación 1",
        capacity: 2,
        hasPrivateBathroom: true,
        isSoldOut: true,
        floor: 1,
        bedType: "2 single beds",
        bathroomNumber: 1,
        bathroomType: "private",
        roomType: "shared",
        roomSize: "small",
        sotiQualification: 6.75,
        beds: 2,
        sharedBathroom: 1,
        quality: 2,
        roomPrice: 1000,
        pricePerPerson: 500,
        imageUrl: "/room-images/Hab 1.png",
        coordinates: {
          x: 70.64,
          y: 67.45,
          width: 9.75,
          height: 21.94,
        },
      },
      {
        id: "floor-1-room-2",
        number: "Habitación 2",
        capacity: 2,
        hasPrivateBathroom: true,
        isSoldOut: true,
        floor: 1,
        bedType: "1 queen bed",
        bathroomNumber: 2,
        bathroomType: "private",
        roomType: "individual",
        roomSize: "large",
        sotiQualification: 10,
        beds: 1,
        sharedBathroom: 1,
        quality: 2,
        roomPrice: 1000,
        pricePerPerson: 1000,
        imageUrl: "/room-images/Hab 2.png",
        coordinates: {
          x: 60.30,
          y: 67.32,
          width: 10.25,
          height: 22.46,
        },
      },
      {
        id: "floor-1-room-3",
        number: "Habitación 3",
        capacity: 2,
        hasPrivateBathroom: true,
        isSoldOut: true,
        floor: 1,
        bedType: "2 single beds",
        bathroomNumber: 3,
        bathroomType: "private",
        roomType: "shared",
        roomSize: "small",
        sotiQualification: 6.75,
        beds: 2,
        sharedBathroom: 1,
        quality: 2,
        roomPrice: 1000,
        pricePerPerson: 500,
        imageUrl: "/room-images/Hab 3.png",
        coordinates: {
          x: 50.05,
          y: 67.59,
          width: 9.66,
          height: 22.73,
        },
      },
      {
        id: "floor-1-room-4",
        number: "Habitación 4",
        capacity: 2,
        hasPrivateBathroom: true,
        floor: 1,
        bedType: "2 single beds",
        bathroomNumber: 4,
        bathroomType: "private",
        roomType: "shared",
        roomSize: "small",
        sotiQualification: 6.75,
        beds: 2,
        sharedBathroom: 1,
        quality: 2,
        roomPrice: 1000,
        pricePerPerson: 500,
        imageUrl: "/room-images/Hab4.jpg",
        coordinates: {
          x: 38.92,
          y: 67.85,
          width: 10.34,
          height: 22.59,
        },
      },
      {
        id: "floor-1-room-5",
        number: "Habitación 5",
        capacity: 2,
        hasPrivateBathroom: true,
        isSoldOut: true,
        floor: 1,
        bedType: "2 single beds",
        bathroomNumber: 5,
        bathroomType: "private",
        roomType: "shared",
        roomSize: "small",
        sotiQualification: 6.75,
        beds: 2,
        sharedBathroom: 1,
        quality: 2,
        roomPrice: 1000,
        pricePerPerson: 500,
        imageUrl: "/room-images/Hab5.jpg",
        coordinates: {
          x: 28.08,
          y: 59.57,
          width: 10.15,
          height: 21.94,
        },
      },
      {
        id: "floor-1-room-6",
        number: "Habitación 6",
        capacity: 2,
        hasPrivateBathroom: false,
        isSoldOut: true,
        floor: 1,
        bedType: "1 queen bed",
        bathroomNumber: 6,
        bathroomType: "shared",
        roomType: "individual",
        roomSize: "large",
        sotiQualification: 8.25,
        beds: 1,
        sharedBathroom: 2,
        quality: 2,
        roomPrice: 850,
        pricePerPerson: 850,
        imageUrl: "/room-images/Hab6.jpg",
        coordinates: {
          x: 17.23,
          y: 23.86,
          width: 24.05,
          height: 11.62,
        },
      },
      {
        id: "floor-1-room-12",
        number: "Habitación 12",
        capacity: 2,
        hasPrivateBathroom: false,
        isSoldOut: true,
        floor: 1,
        bedType: "2 single beds",
        bathroomNumber: 6,
        bathroomType: "shared",
        roomType: "shared",
        roomSize: "small",
        sotiQualification: 5,
        beds: 2,
        sharedBathroom: 2,
        quality: 1,
        roomPrice: 850,
        pricePerPerson: 425,
        imageUrl: "/room-images/Hab 12.png",
        coordinates: {
          x: 28.77,
          y: 36.12,
          width: 7.88,
          height: 16.42,
        },
      },
    ],
  },
  {
    floorNumber: 2,
    floorPlanPath: "/floor-plan-5.svg", // New floor plan 5
    rooms: [
      {
        id: "floor-2-room-7",
        number: "Habitación 7",
        capacity: 2,
        hasPrivateBathroom: true,
        currentOccupancy: 1,
        isSoldOut: true,
        floor: 2,
        bedType: "2 single beds",
        bathroomNumber: 7,
        bathroomType: "private",
        roomType: "shared",
        roomSize: "small",
        sotiQualification: 6.75,
        beds: 2,
        sharedBathroom: 1,
        quality: 1,
        roomPrice: 800,
        pricePerPerson: 400,
        imageUrl: "/room-images/hab 7.png",
        coordinates: {
          x: 28.08,
          y: 46.96,
          width: 10.94,
          height: 14.06,
        },
      },
      {
        id: "floor-2-room-8",
        number: "Habitación 8",
        capacity: 2,
        hasPrivateBathroom: false,
        isSoldOut: true,
        floor: 2,
        bedType: "1 queen bed",
        bathroomNumber: 8,
        bathroomType: "shared",
        roomType: "individual",
        roomSize: "large",
        sotiQualification: 8.25,
        beds: 1,
        sharedBathroom: 2,
        quality: 2,
        roomPrice: 800,
        pricePerPerson: 800,
        imageUrl: "/room-images/hab 8.png",
        coordinates: {
          x: 35.98,
          y: 75.00,
          width: 28.60,
          height: 14.65,
        },
      },
      {
        id: "floor-2-room-13",
        number: "Habitación 13",
        capacity: 2,
        hasPrivateBathroom: false,
        isSoldOut: true,
        floor: 1,
        bedType: "2 single beds",
        bathroomNumber: 8,
        bathroomType: "shared",
        roomType: "shared",
        roomSize: "small",
        sotiQualification: 5,
        beds: 2,
        sharedBathroom: 2,
        quality: 1,
        roomPrice: 850,
        pricePerPerson: 425,
        imageUrl: "/room-images/Hab 13.png",
        coordinates: {
          x: 28.47,
          y: 61.81,
          width: 10.34,
          height: 19.05,
        },
      },
    ],
  },
];

// Legacy export for backward compatibility (uses floor 1)
export const rooms: Room[] = floorsData[0]?.rooms || [];

